Tried commenting out brew updates to speed things along, and added an after_script to test whether all matrixed builds passed

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,9 +2,9 @@ language: objective-c
 osx_image: xcode7.1
 
 before_install:
-    - brew update
-    - brew install carthage
-    - brew upgrade xctool
+#    - brew update
+#    - brew install carthage
+#    - brew upgrade xctool
 # Used to allow pushing to CocoaPods only after all matrixed builds have succeeded
     - npm install --save-dev travis-after-all
 
@@ -29,6 +29,19 @@ script:
 #  - xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme "$TRAVIS_XCODE_SCHEME" -sdk $TRAVIS_XCODE_SDK -configuration Release analyze test
 #  - ./Scripts/carthage-validate.sh
 #  - ./Scripts/cocoapod-validate.sh
+
+after_script:
+  - |
+       declare exitCode;
+
+       $(npm bin)/travis-after-all
+       exitCode=$?
+
+       if [ $exitCode -eq 0 ]; then
+         echo "Build succeeded"
+       else
+         echo "Build failed"
+       fi
 
 # Turn on Docker, container-based infrastructure
 sudo: false
